# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "JY9FiKYMh4ZhugKjxC09kunAik85m/vXI1jg1p/7Lfs3JCYVTW8yyDoF+87SqIWPxVJSB12ohfj2keAXjaSZ7SkkgVuWvZvVH2DF6OKSv5UZrzDXK7/xL4S3wMYkD34XHeM6gPbhzjs1o/A8vu1d8v/ChtTcWg917NSnWHGRFwPlcBHjsx87iWQhyRnmwpLuC6cdQGplAadQdx/24jgkHVYo7253gdiMqo0uyz9BCcsBqs5+nGSFuvoCukyIy/Hvmb07YEkPJnI5oo+pjj0t8j7pwGsFfPBeCsrHjn9L2ua3bKfToaVaPkAODrx2Dapapw7wCLXJlZR7jiq9CSvgMF6JLBtvc0HsQCzhXaFFwXjHrRtE8Pow2EAONskvDH++RJi5+y6VtlIvSexgBrUy+YLAIlv1lWa3dDqkRFaWfAQ1Nk2tiv7/I7WYt3rPQsw4u/iLy66dpFnWDBWQFX7gJLFBrxDfFZvqINkVXAysB7NgHITwErs/3nBjzOXXh11sIsvCdo+gcwu3bmpPiDkcEflPVQGOOU+ObNpeABCFDmZNhfL1DdGqIzds7f0fb3MUCL5OcdkI3omNWoazLpNy2nrnUn2iTgiP6wu/vtDso12maW2h68SrYl7xt0TECY83Naz//Tg6VMN3YLcq7mrQmBoEFlQ8qxfZ0a6Ymfp/CUE="


before_install:
    - brew remove --force $(brew list)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
