travis:
  secure:
    BINSTAR_TOKEN: kri9QFflL+e9MUp8SkwSznnAD27DFzSkc+t3hTjVNIIe6AA7NtinqFjL2p5ZkFEksAeJrpY64dLJtMKfLoJvoWle9zaGxmeK4bvPdlXVPYqoxsutdmOijRpCJ6dvVQVeI+s+0I4QKtd6+NWDwpgSCzu0jZduffUy0X9a5eFX/e+hhLaat+SDrkOsgj9E2KfJMfqu/P7yu6SvXjpzxtPTx1DI9EmBz440Ncpv9I0L+YtwZhTFIETQ7fPumH7ungzEBATIFCGOyPbvX4nPUffP631p5Ow605ygTUyG52gylXZw1FFk72kFZIyDAj6PlvDiOHDrgWTgVcbWGzGQ2KjinRSN6IJx/XJNgCZ5dO47A0faM2iikPMT9nNlOPbNbYe9U+SbUgldQlCHbE/Nf+WX4bcEiboxuR6dTdMmGxAaEj8mffVJKszD4fQcO6bFif1/NW2jHlPWDqrgnpaxuW2CF4mZyMLG+9Oh+d64vciphqRZdG2J2LVooJeryO9hGujYMVtqoEfcsbBmOJ4NZyq07kDacnerZbY0dkEORjQ0mhcXrd3052tN0GT5/GgWeciUXwGlzzLX83RZFa4Mvqcx5VT4kxoTRNPkqT0Wj+fzupLBEN9vOBhjb9virY3N3rECHynIcPR5HeggBLR/CShTL9LunSSOjsqc63RY0aHVafQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
