travis:
  secure:
    BINSTAR_TOKEN: JY9FiKYMh4ZhugKjxC09kunAik85m/vXI1jg1p/7Lfs3JCYVTW8yyDoF+87SqIWPxVJSB12ohfj2keAXjaSZ7SkkgVuWvZvVH2DF6OKSv5UZrzDXK7/xL4S3wMYkD34XHeM6gPbhzjs1o/A8vu1d8v/ChtTcWg917NSnWHGRFwPlcBHjsx87iWQhyRnmwpLuC6cdQGplAadQdx/24jgkHVYo7253gdiMqo0uyz9BCcsBqs5+nGSFuvoCukyIy/Hvmb07YEkPJnI5oo+pjj0t8j7pwGsFfPBeCsrHjn9L2ua3bKfToaVaPkAODrx2Dapapw7wCLXJlZR7jiq9CSvgMF6JLBtvc0HsQCzhXaFFwXjHrRtE8Pow2EAONskvDH++RJi5+y6VtlIvSexgBrUy+YLAIlv1lWa3dDqkRFaWfAQ1Nk2tiv7/I7WYt3rPQsw4u/iLy66dpFnWDBWQFX7gJLFBrxDfFZvqINkVXAysB7NgHITwErs/3nBjzOXXh11sIsvCdo+gcwu3bmpPiDkcEflPVQGOOU+ObNpeABCFDmZNhfL1DdGqIzds7f0fb3MUCL5OcdkI3omNWoazLpNy2nrnUn2iTgiP6wu/vtDso12maW2h68SrYl7xt0TECY83Naz//Tg6VMN3YLcq7mrQmBoEFlQ8qxfZ0a6Ymfp/CUE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
